### ISSUE TITLE
Visualization of reconstructed images in LLIE

### ISSUE THREAD

**Issue by skyqwe123** [manman1995/Deep-Fourier-Upsampling#5]
@manman1995  Thank you very much for your great work!
In the process of learning, I have encountered a problem and would like to consult you.

When the following configuration is used in the LOL dataset training, the input image is normalized to [0,1], and can be directly multiplied by 255 during visualization. However, there are some problems in the visualization of the output image, I would like to consult you how to visualize the reconstructed images normally.

config_file:
Deep-Fourier-Upsampling/LLIE/options/train/LLIE/SID_UpSampling_Area.yml

reconstructed image:  
In Deep-Fourier-Upsampling/LLIE/basicsr/archs/SID_UpSampling_Area_arch.py
out = self.conv10_1(conv9)   # reconstructed image

**Comment by manman1995** [comment]
Thanks for your attention. We mistakenly added two parameters in the original  configuration file, and we have updated. You can use the following code to validate the pre-trained or your own models. 

python /LLIE/test.py -opt /LLIE/options/test/LLIE/SID.yml
python /LLIE/test.py -opt /LLIE/options/test/LLIE/DRBN.yml
